name: termansi
description: Collection of ANSI escape sequences definitions for terminal applications.
version: 0.3.1
repository: https://github.com/kascote/termkit/tree/master/packages/termansi
homepage: https://github.com/kascote/termkit
issue_tracker: https://github.com/kascote/termkit/issues
documentation: https://github.com/kascote/termkit/tree/master/packages/termansi#readme
topics: [console, terminal, ansi]
platforms:
  linux:
  macos:

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
